# Generated by Django 5.1.4 on 2025-01-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='iv',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='keys',
            name='private_key_file',
            field=models.BinaryField(),
        ),
    ]
