# Generated by Django 5.1.4 on 2025-01-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_keys_iv_alter_keys_private_key_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='public_key_file',
            field=models.BinaryField(),
        ),
    ]
